name: PMC WaRP
favicon: null
layout_spectrum: 0.9511278
typography_spectrum: 0.6611174
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030000'
    - '#5C0302'
    - '#D8391E'
    - '#F2914B'
    - '#FB9103'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.7846402
  rhythmicContrast: 0.5
purpose: []
