name: PMC WaRP
favicon: null
layout_spectrum: 0.74875
typography_spectrum: 0.9975
title: PMC Workforce and Readiness Professionals LLC
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#8d444b'
    - '#c89c93'
    - '#ae6f66'
    - '#323232'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.7846402
  rhythmicContrast: 0.5
purpose: []
